---
title: "Don't Mess with Texas: data from Texas department of corrections"
output: github_document
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
library(knitr)
library(rmdformats)
library(tidyverse)
library(devtools)
library(hrbrthemes)
# figs folder
if (!file.exists("figs")) {
  dir.create("figs")
}
# chunk options
knitr::opts_chunk$set(
  echo = TRUE, # show/hide all code
  eval = FALSE, # hide results
  tidy = FALSE, # cleaner code printing
  comment = "#> ", # better console printing
  message = TRUE, # show messages
  warning = FALSE, # show warnings
  size = "small", # size of the text
  fig.path = "figs/", # location of files
  fig.height = 7.5, # height of figures
  fig.width = 10 # width of figures
) # width of figures
# knit options
knitr::opts_knit$set(
  width = 78,
  progress = FALSE
)
# base options
base::options(
  tibble.print_max = 25,
  tibble.width = 78,
  max.print = 999999,
  scipen = 100000000
)
# plot theme ------
ggplot2::theme_set(theme_ipsum_tw(
  base_size = 9,
  strip_text_size = 9,
  axis_title_size = 13,
  plot_title_size = 17,
  subtitle_size = 13,
  base_family = "Ubuntu",
  # "JosefinSans-LightItalic"
  strip_text_family = "TitilliumWeb-Regular",
  axis_title_family = "TitilliumWeb-Regular",
  subtitle_family = "TitilliumWeb-Regular",
  plot_title_family = "JosefinSans-Regular"
))
```


These data come from the [Texas Department of Criminal Justice](https://www.tdcj.texas.gov/index.html) website that holds death row information on executed [offenders](https://www.tdcj.texas.gov/death_row/dr_executed_offenders.html).

## Executions in Texas

Capital punishment in Texas has a long history (read about it [here](https://en.wikipedia.org/wiki/Capital_punishment_in_Texas)). At the time of this writing (**`r Sys.Date()`**), Texas has carried out more than 1/3 of the total executions in the United States. The project tells the story of capitol punishment in Texas (and the US). I created this project to raise awareness about the reality of state-sanctioned deaths, and to try and understand more about why Texas is such an outlier with respect to capitol punishment.

I constantly stumble across data on websites I'd like to use in a visualization or analyze. R comes with two great packages for scraping data from .html tables (`rvest` and `xml`). In order to download data, sometimes each file needs to be downloaded onto your local machine. The `purrr` package has quite a few excellent functions for iteration to help with this.

## Texas death row executed offenders website

Texas Department of Criminal Justice keeps records of every inmate they execute. We are going to scrape the data found
[here](http://www.tdcj.state.tx.us/death_row/dr_executed_offenders.html).
